language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: VL/0gFmQcBdFuDepkVL7giNBQ4rfks54SD0IPTkCF7sC8fU7hlcoYcm8vzTTbEpIcAGcqpqY9ktng9MI/KFrErlKQO3WUlrRQHHE8DHmnToBTO02at57wefQcH/DWKGySSwwjiBy8IFYBKJ+T9driH64/RJWRHeAYudqMLJxm72BSadW1a4Rynee8F0HPMTZ88qycJSLkFPt70+lSYvNF//0yDOLD0aaIjlXCzG/aJ8H9VytPSaWOlkRZIknQtp1II07hdAyT4uwX46+QJCCCL7ZELy+FhsFWp9Z48NkRA3k+/ZnktmUylJXW6z79tT9FACKeq6loDVS5lcIz+rDYFXxz/V6DeO/5bmbgYAMCS5wPIxkN7BHLl+RC26ZifXHlkGlwwwW2dSUOBXVejVN4UJAIpOWXU4IdY5JAd2yaaYIFBVQQgK/Go/eqUQduu2ootY7NEAtCch++288lqoEdr6UbO8ywax95mVuT5mtDQHNBFO0Ek9o6fvni0+fr05ZIfwdWSCZWZdxp4r7eFt01Kk/INkuF1AjhUmdOvnUbABxyovtHupJ9ijcHctr3LeW4iHLAPaKufeblSuWw+RJcCDKs8yQ9issgApJgauyMbQ8+GxD6rn/nGNHKGxuxxFIAvcPZMtK4k1bQkPaj45UrX4D+32BAjR43AfOitgvN6M=
  app: askmee
